remote_theme: CoderTonyChan/tonydesign-jekyll
google_analytics: UA-135626320-2
background-image: http://sf6-tccdn-tos.pstatp.com/obj/tuchong-avatar/h_2301626_1

# include: 
#   enable: true
#   html: "gallery.html"

images: 
    - title: 日常
      src: 'https://photo.tuchong.com/2301626/ft640/209322359.jpg'
      w: 640
      h: 480
    - title: 新年
      src: 'https://photo.tuchong.com/2301626/ft640/218693985.jpg'
      w: 480
      h: 639
    - title: 漫展
      src: 'https://photo.tuchong.com/2301626/ft640/559284591.jpg'
      w: 621
      h: 480
    - title: 漫展
      src: 'https://photo.tuchong.com/2301626/ft640/559284591.jpg'
      w: 621
      h: 480
    - title: 漫展
      src: 'https://photo.tuchong.com/2301626/ft640/559284591.jpg'
      w: 621
      h: 480
    - title: 漫展
      src: 'https://photo.tuchong.com/2301626/ft640/559284591.jpg'
      w: 621
      h: 480