remote_theme: CoderTonyChan/tonydesign-jekyll
google_analytics: UA-135626320-2
background-image: http://sf6-tccdn-tos.pstatp.com/obj/tuchong-avatar/h_2301626_1
include: gallery.html

images: 
    - title: 爱人
      src: 'https://photo.tuchong.com/2301626/ft640/209322359.jpg'
    - title: 爱人
      src: 'https://photo.tuchong.com/2301626/ft640/209322359.jpg'
    - title: 爱人
      src: 'https://photo.tuchong.com/2301626/ft640/209322359.jpg'

